import {
  BROWSER_CALL_START_MESSAGE,
  resolveExecutionTimezone,
  type ExecutionMode
} from "@coreai/shared";
import { runAgentWorkflow } from "../agent-runtime/graph-runner";
import {
  createArchitectTestProviders,
  createBusinessTestProviders,
  type AgentProviders,
  type CalendarBookingEventDetails
} from "../agent-runtime/provider-adapters";
import type { AgentMessage } from "../agent-runtime/runtime-context";
import { calendarError, publicCalendarError } from "./calendar-errors";

/**
 * Conversation test — a thin wrapper over the shared agent runtime, used by
 * BOTH the Architect dry run and the Business installed-agent test. The same
 * runtime (graph runner + node handlers) powers the live call flow; only the
 * provider adapters differ per execution mode.
 */

export type ArchitectConversationRole = "user" | "assistant";

export type ArchitectConversationMessage = {
  role: ArchitectConversationRole;
  content: string;
  createdAt?: string;
};

export type ArchitectConversationTestContext = {
  businessName?: string;
  businessType?: string;
  assistantName?: string;
  callerName?: string;
  callerPhone?: string;
  calendarId?: string;
  timeZone?: string;
  appointmentService?: string;
  /** Test-form pre-selected date ("YYYY-MM-DD") — seeds the conversation. */
  requestedDate?: string;
  /** Test-form pre-selected time ("HH:mm", 24h). */
  requestedTime?: string;
  services?: string[];
  faqs?: string[];
};

export type ArchitectConversationToolCall = {
  name: string;
  status: "simulated" | "skipped" | "error";
  message: string;
  input?: Record<string, unknown>;
  output?: Record<string, unknown>;
};

export type ArchitectConversationNodeLog = {
  nodeId: string;
  label: string;
  status: "success" | "waiting" | "error" | "skipped";
  message: string;
  output?: unknown;
};

export type ConversationTestConfigError = {
  code: string;
  message: string;
  remediation: string;
};

export type ArchitectConversationTestResult = {
  reply: string;
  transcript: ArchitectConversationMessage[];
  executedNodes: ArchitectConversationNodeLog[];
  toolCalls: ArchitectConversationToolCall[];
  finalOutput: Record<string, unknown>;
  simulated: true;
  executionMode: ExecutionMode;
  timeZone: string | null;
  testSessionId: string | null;
  /** Calendar event created/simulated by this turn's booking, if any. */
  calendarEvent: CalendarBookingEventDetails | null;
  /** Set when this turn's booking failed (e.g. CALENDAR_NOT_CONNECTED) —
   * shown as an actionable error panel; never a silent fallback. */
  calendarError: ConversationTestConfigError | null;
  /** Set when the test could not run safely (e.g. missing/invalid timezone). */
  configError: ConversationTestConfigError | null;
};

/** Identity of the business under test — required for BUSINESS_TEST mode. */
export type ConversationTestBusinessIdentity = {
  businessId: string;
  installedAgentId?: string;
};

function cleanHistory(history: ArchitectConversationMessage[] | undefined): AgentMessage[] {
  if (!Array.isArray(history)) return [];

  return history
    .filter((item) => item.role === "user" || item.role === "assistant")
    .map((item) => ({
      role: item.role,
      content: item.content.trim().slice(0, 4000),
      createdAt: item.createdAt
    }))
    .filter((item) => item.content.length > 0)
    .slice(-30);
}

function emptyResult(params: {
  executionMode: ExecutionMode;
  workflowId: string;
  transcript: ArchitectConversationMessage[];
  message: string;
  reply: string;
  testSessionId: string | null;
  nodeLog: ArchitectConversationNodeLog;
  configError: ConversationTestConfigError | null;
}): ArchitectConversationTestResult {
  const now = new Date().toISOString();

  return {
    reply: params.reply,
    transcript: [
      ...params.transcript,
      { role: "user", content: params.message, createdAt: now },
      { role: "assistant", content: params.reply, createdAt: now }
    ],
    executedNodes: [params.nodeLog],
    toolCalls: [],
    finalOutput: { workflowId: params.workflowId, reply: params.reply },
    simulated: true,
    executionMode: params.executionMode,
    timeZone: null,
    testSessionId: params.testSessionId,
    calendarEvent: null,
    calendarError: null,
    configError: params.configError
  };
}

export async function runArchitectConversationTest({
  userId,
  workflowId,
  workflowJson,
  message,
  history,
  testContext,
  executionMode = "ARCHITECT_DRY_RUN",
  testSessionId,
  useTestCalendar,
  businessIdentity
}: {
  userId: string;
  workflowId: string;
  workflowJson: unknown;
  message: string;
  history?: ArchitectConversationMessage[];
  testContext?: ArchitectConversationTestContext;
  /** ARCHITECT_DRY_RUN (default) or BUSINESS_TEST. Never LIVE. */
  executionMode?: Extract<ExecutionMode, "ARCHITECT_DRY_RUN" | "BUSINESS_TEST">;
  /** Groups this test's records; generated by the caller/route. */
  testSessionId?: string;
  /** Architect only: create real events in the architect's own test calendar. */
  useTestCalendar?: boolean;
  /** Required when executionMode is BUSINESS_TEST. */
  businessIdentity?: ConversationTestBusinessIdentity;
}): Promise<ArchitectConversationTestResult> {
  const transcriptHistory = cleanHistory(history);
  const cleanMessage = message.trim();
  const isCallStart = cleanMessage === BROWSER_CALL_START_MESSAGE;
  const session = testSessionId?.trim() || null;

  // Central timezone decision — never a silent server-zone fallback. A missing
  // or invalid timezone blocks the test with a remediation message instead of
  // booking at an assumed time.
  const timezoneResult = resolveExecutionTimezone({
    executionMode,
    selectedTestTimezone: executionMode === "ARCHITECT_DRY_RUN" ? testContext?.timeZone : null,
    businessTimezone: executionMode === "BUSINESS_TEST" ? testContext?.timeZone : null
  });

  if (!timezoneResult.ok) {
    const error = publicCalendarError(calendarError(timezoneResult.errorCode));
    const reply =
      executionMode === "ARCHITECT_DRY_RUN"
        ? "Select a valid test timezone before running this test."
        : "Set your business timezone in the Configure step before testing.";

    return emptyResult({
      executionMode,
      workflowId,
      transcript: transcriptHistory,
      message: cleanMessage,
      reply,
      testSessionId: session,
      nodeLog: {
        nodeId: "timezone",
        label: "Timezone configuration",
        status: "error",
        message: error.message
      },
      configError: { code: error.code, message: error.message, remediation: error.remediation }
    });
  }

  const timeZone = timezoneResult.timeZone;

  // The exact supplied service name is retained (trimmed + bounded). The
  // generic fallback applies only when nothing was supplied.
  const suppliedService = testContext?.appointmentService?.trim().slice(0, 160) ?? "";
  const appointmentService = suppliedService || "Appointment";

  const business = {
    name: testContext?.businessName?.trim() || "Sample Business",
    type: testContext?.businessType?.trim() || "service business",
    assistantName: testContext?.assistantName?.trim() || "",
    timezone: timeZone,
    calendarId: testContext?.calendarId?.trim() || "primary",
    appointmentService,
    services:
      Array.isArray(testContext?.services) && testContext.services.length > 0
        ? testContext.services
        : [appointmentService, "General inquiry"],
    faqs:
      Array.isArray(testContext?.faqs) && testContext.faqs.length > 0
        ? testContext.faqs
        : ["Pricing depends on the selected service.", "Urgent requests should be escalated to the team."]
  };

  const caller = {
    name: testContext?.callerName?.trim() || "Test caller",
    phone: testContext?.callerPhone?.trim() || "+15555550100"
  };

  const hasNodes = Array.isArray((workflowJson as { nodes?: unknown[] } | null)?.nodes)
    ? ((workflowJson as { nodes: unknown[] }).nodes.length > 0)
    : false;

  if (!hasNodes) {
    return emptyResult({
      executionMode,
      workflowId,
      transcript: transcriptHistory,
      message: cleanMessage,
      reply: "Add at least one node before testing this agent.",
      testSessionId: session,
      nodeLog: { nodeId: "empty", label: "Empty workflow", status: "error", message: "No nodes found." },
      configError: null
    });
  }

  let providers: AgentProviders;

  if (executionMode === "BUSINESS_TEST") {
    if (!businessIdentity?.businessId) {
      throw new Error("BUSINESS_TEST requires businessIdentity.businessId");
    }

    providers = createBusinessTestProviders({
      ownerUserId: userId,
      businessId: businessIdentity.businessId,
      installedAgentId: businessIdentity.installedAgentId,
      workflowId,
      testSessionId: session ?? undefined,
      businessName: business.name
    });
  } else {
    providers = createArchitectTestProviders({
      userId,
      workflowId,
      testSessionId: session ?? undefined,
      businessName: business.name,
      useTestCalendar: useTestCalendar === true
    });
  }

  const result = await runAgentWorkflow({
    workflowId,
    workflowJson,
    mode: executionMode === "BUSINESS_TEST" ? "business_test" : "architect_test",
    input: {
      channel: "browser_voice",
      event: isCallStart ? "call_start" : "user_message",
      message: cleanMessage,
      history: transcriptHistory,
      business,
      caller,
      requestedDate: testContext?.requestedDate?.trim() || undefined,
      requestedTime: testContext?.requestedTime?.trim() || undefined
    },
    providers
  });

  const availableSlots = result.variables["calendar.available_slots"];

  console.log("[conversation-test] turn", {
    workflowId,
    executionMode,
    timeZone,
    assistantName: business.assistantName || "(resolved from node config)",
    businessName: business.name,
    capabilities: result.capabilities,
    slotsReturned: Array.isArray(availableSlots) ? availableSlots.length : 0,
    executedNodes: result.executedNodes.map((log) => log.label)
  });

  const bookingCall = result.toolCalls.find((call) => call.name === "calendar.book_appointment");
  const bookingOutput =
    bookingCall?.output && typeof bookingCall.output === "object"
      ? (bookingCall.output as Record<string, unknown>)
      : null;
  const calendarEvent = bookingOutput && "event" in bookingOutput
    ? (bookingOutput.event as CalendarBookingEventDetails)
    : null;
  const bookingError: ConversationTestConfigError | null =
    bookingCall?.status === "error" && typeof bookingOutput?.errorCode === "string"
      ? {
          code: bookingOutput.errorCode,
          message: bookingCall.message,
          remediation: typeof bookingOutput.remediation === "string" ? bookingOutput.remediation : "Try again."
        }
      : null;

  const now = new Date().toISOString();
  const transcript: ArchitectConversationMessage[] = isCallStart
    ? [...transcriptHistory, { role: "assistant", content: result.reply, createdAt: now }]
    : [
        ...transcriptHistory,
        { role: "user", content: cleanMessage, createdAt: now },
        { role: "assistant", content: result.reply, createdAt: new Date().toISOString() }
      ];

  return {
    reply: result.reply,
    transcript,
    executedNodes: result.executedNodes,
    toolCalls: result.toolCalls,
    finalOutput: {
      workflowId,
      reply: result.reply,
      businessName: business.name,
      assistantName: business.assistantName,
      capabilities: result.capabilities,
      executedNodeIds: result.executedNodes.map((log) => log.nodeId),
      variables: result.variables,
      simulated: true,
      executionMode,
      timeZone
    },
    simulated: true,
    executionMode,
    timeZone,
    testSessionId: session,
    calendarEvent,
    calendarError: bookingError,
    configError: null
  };
}
