/**
 * THE CONNECTOR CONTRACT — one file describes a connector, one engine runs them all.
 *
 * Before this, adding a service meant editing eight places: the registry, the
 * runner, the setup form, the dashboard, the cost, the failure handling, the
 * admin pricing and the tests. Eight chances to do it differently from last
 * time — which is how twenty hand-written handlers ended up in one 6,708-line
 * file, none of them agreeing on what to do when something breaks.
 *
 * A connector now declares nine things and provides one function. Everything
 * else — the business's setup form, their dashboard, the price ceiling, the
 * retries, the throttling, the daily health check, what an architect may test
 * — is generated by READING this declaration. Nothing is built per connector.
 *
 * Three rules shaped every decision here:
 *
 *  1. NAME THE JOB, NOT THE COMPANY. A connector declares that it
 *     "finds work emails", not that it "is Apollo". Apollo could be bought and
 *     shut down; an agent that asked for the job survives that, an agent that
 *     asked for the company dies with it.
 *
 *  2. PRETENDING TO WORK MUST BE IMPOSSIBLE. A connector cannot report success
 *     without returning what it declared it produces — the engine checks. This
 *     is the exact failure that had a calendar node inventing three appointment
 *     times when Google was unreachable, and logging it green.
 *
 *  3. WHAT AGES, DECLARE AS A KIND, NOT A VALUE. Credentials are turning from
 *     keys into OAuth tokens. Pricing is turning from per-call into per-token.
 *     So a connector says what KIND of credential it needs and what STYLE of
 *     metering it has — never "a key in a box" or a hardcoded rate.
 */

/* -------------------------------------------------------------------------- */
/* 01 · Who I am, and what job I do                                            */
/* -------------------------------------------------------------------------- */

/**
 * The job a connector performs, independent of who performs it.
 *
 * Apollo, Hunter and Prospeo are three companies doing ONE job. An agent asks
 * for the job; the platform picks a provider. Swapping providers then costs one
 * line instead of rebuilding every agent that used the old one.
 */
export type ConnectorJob =
  | "find-work-emails"
  | "verify-email"
  | "send-email-campaign"
  | "read-campaign-replies"
  | "scrape-website"
  | "enrich-company"
  | "send-message"
  | "place-call"
  | "book-meeting"
  | "search-web"
  | "custom";

export type ProviderInfo = {
  /** The company, in the words a person would use. */
  name: string;
  /** Where their documentation lives — the first thing a maintainer opens. */
  docsUrl: string;
  /** Their terms. Read before ever reselling their data under our own key. */
  termsUrl?: string;
  /**
   * The version of THEIR API this heart was written against.
   *
   * The single most useful field in this file. When a provider deprecates a
   * version, this is what tells a maintainer which connectors are affected —
   * without it, the answer is "read all of them".
   */
  apiVersion: string;
  /** When a human last confirmed this heart matches their current docs. */
  lastVerified: string;
};

/* -------------------------------------------------------------------------- */
/* 02 · What I need to run, and who supplies it                                */
/* -------------------------------------------------------------------------- */

/**
 * What KIND of credential, never the credential itself.
 *
 * Written as a kind because the industry is moving: today an API key, next
 * year an OAuth token that expires in an hour. A contract that assumed "a
 * string in a box" would need rewriting for every connector.
 */
export type CredentialKind = "api_key" | "oauth2" | "basic_auth" | "bearer_token" | "none";

export type PlatformNeed = {
  key: string;
  label: string;
  kind: CredentialKind;
  /** Shown to the admin who has to go and find it. */
  help: string;
  /** False when the connector can run without it (a free tier, say). */
  required: boolean;
};

/** A question put to a person — an architect or a business. */
export type ConnectorField = {
  key: string;
  label: string;
  help: string;
  kind:
    | "text"
    | "longtext"
    | "number"
    | "phone"
    | "email"
    | "url"
    | "date"
    | "time"
    | "choice"
    | "list"
    | "file"
    | "secret";
  required: boolean;
  choices?: string[];
  placeholder?: string;
  /** A default the person can change. Never a value they must not see. */
  defaultValue?: string | number;
};

/** An account the BUSINESS connects themselves — their Google, their Gmail. */
export type ConnectorAccount = {
  connector: string;
  label: string;
  help: string;
  scopes?: string[];
  optional?: boolean;
};

export type ConnectorNeeds = {
  /** Ours. Lives in the admin panel, never in the builder. */
  platform: PlatformNeed[];
  /**
   * The architect's decisions, made once for everyone who installs the agent.
   *
   * Manus's version of this design had two owners, business and admin. There
   * are three. The architect is the person who BUILDS on this platform, and
   * leaving them out breaks the model the whole product rests on.
   */
  architect: ConnectorField[];
  /** The business's own details. This list becomes their setup form. */
  business: ConnectorField[];
  /** Accounts the business connects with a button. */
  accounts: ConnectorAccount[];
};

/* -------------------------------------------------------------------------- */
/* 03 · What I produce                                                         */
/* -------------------------------------------------------------------------- */

/**
 * A value later steps can use.
 *
 * `sample` is not decoration: it is what lets the AI doors translate between
 * two steps that were never designed for each other, and what the engine
 * checks the heart's answer against.
 */
export type ConnectorOutput = {
  key: string;
  label: string;
  kind: "text" | "number" | "boolean" | "list" | "object" | "date";
  /** A realistic example. Used for translation and for validation. */
  sample: unknown;
  /** True when a run is meaningless without it — the engine enforces this. */
  required: boolean;
};

/* -------------------------------------------------------------------------- */
/* 04 · What one run costs                                                     */
/* -------------------------------------------------------------------------- */

export type CostModel = {
  /** HOW it is charged, not how much — the how-much moves, the how does not. */
  style: "free" | "per_call" | "per_result" | "per_token" | "per_minute" | "per_month";
  /** Roughly, in US cents, so a ceiling can be enforced before the bill lands. */
  estimateCents: number;
  /** What one unit is, in plain words: "per lead found". */
  unit: string;
  /** Who is billed: the provider bills the business directly, or bills us. */
  billedTo: "business" | "platform";
  note?: string;
};

/* -------------------------------------------------------------------------- */
/* 05 · What to do when I fail                                                 */
/* -------------------------------------------------------------------------- */

export type FailurePolicy = {
  /**
   * retry — try again, it may be temporary.
   * skip  — this one item failed, carry on with the rest.
   * stop  — end the whole run; continuing would be wrong or expensive.
   */
  onError: "retry" | "skip" | "stop";
  maxRetries: number;
  backoffMs: number;
  /**
   * Errors that must NEVER be retried.
   *
   * A wrong key is still wrong on the fourth attempt, and retrying a "payment
   * required" four times is just four times the bill.
   */
  neverRetry: number[];
  /**
   * What the business is told when it finally fails. Written for them, not for
   * a developer — and never implying anything happened that did not.
   */
  humanMessage: string;
};

/* -------------------------------------------------------------------------- */
/* 06 · My limits                                                              */
/* -------------------------------------------------------------------------- */

export type ConnectorLimits = {
  callsPerMinute: number;
  callsPerDay: number;
  /** How many may be in flight at once for one business. */
  concurrent: number;
  /** For paged work: how many results to ask for at a time. */
  pageSize?: number;
  /** A hard ceiling on pages, so a runaway list cannot spend forever. */
  maxPages?: number;
};

/* -------------------------------------------------------------------------- */
/* 07 · What I must never do                                                   */
/* -------------------------------------------------------------------------- */

/**
 * The rules that protect the person at the other end, and the platform.
 *
 * NOT the same as a business setting. A business may choose to call fewer
 * people; a business may not choose to call people who never agreed. These are
 * enforced by the engine — a heart cannot switch them off, and neither can an
 * architect.
 */
export type ConnectorRules = {
  /** A consent record must exist for this person before we reach them. */
  requiresConsent?: boolean;
  /** Every message must carry a working way out. */
  requiresUnsubscribe?: boolean;
  /** Countries this connector must refuse to operate on. */
  blockedCountries?: string[];
  /** The most this may do for one business in a day, whatever they set. */
  hardDailyCap?: number;
  /** Testing may only reach an identity the architect has proven is theirs. */
  testOnlyToVerifiedIdentity?: boolean;
  /** Anything else a maintainer must know, in plain words. */
  notes?: string[];
};

/* -------------------------------------------------------------------------- */
/* 08 · How to check I still work                                              */
/* -------------------------------------------------------------------------- */

/**
 * The daily self-test that replaces a human reading changelogs.
 *
 * A person watching for a provider's breaking change does it badly: they are
 * scanning release notes hoping to catch one line, for something that happens
 * twice a year. A tiny known request, run every day, catches the same thing
 * and never goes on holiday. The human still fixes it — they just stop being
 * the alarm.
 */
export type HealthProbe = {
  /** How often to check. */
  everyHours: number;
  /** The output keys the probe's answer must still contain. */
  expectKeys: string[];
  /** What it means for the platform when this fails. */
  severity: "breaks-agents" | "degrades" | "informational";
};

/* -------------------------------------------------------------------------- */
/* 09 · What shape of work I am                                                */
/* -------------------------------------------------------------------------- */

/**
 * immediate — answers in a moment.
 * paged     — returns results a page at a time.
 * polled    — takes minutes; start it, come back for the answer.
 * inbound   — the PROVIDER calls US. Not the node running: the world knocking.
 *
 * All four exist in the first agent this standard will serve: scraping is slow,
 * lead search is paged, and Instantly pushes replies to a webhook. A design
 * that only knew request-and-answer would be rebuilt within a week.
 */
export type ExecutionStyle = "immediate" | "paged" | "polled" | "inbound";

/* -------------------------------------------------------------------------- */
/* The heart, and the contract that surrounds it                               */
/* -------------------------------------------------------------------------- */

/** What the engine hands the heart. Everything already resolved and checked. */
export type HeartContext = {
  /** Values from all three owners, merged and validated. */
  config: Record<string, unknown>;
  /** The resolved credential — the heart never looks one up itself. */
  credentials: Record<string, string>;
  /** Which page we are on, for paged work. */
  page: number;
  /** A cursor the previous page returned, when the provider uses one. */
  cursor?: string;
  /** Rehearsal. A heart MUST NOT touch the outside world when this is true. */
  isTest: boolean;
  /** Structured logging. The heart never writes to the console. */
  log: (message: string, detail?: unknown) => void;
};

export type HeartResult = {
  /** Keyed by the `key` of each declared output. Checked before it is trusted. */
  outputs: Record<string, unknown>;
  /** For paged work: is there more to fetch? */
  morePages?: boolean;
  /** A cursor to hand to the next page. */
  cursor?: string;
  /** How many billable units this call actually consumed, if known. */
  unitsUsed?: number;
};

/** The one function a connector author writes. */
export type Heart = (context: HeartContext) => Promise<HeartResult>;

/**
 * A whole connector.
 *
 * Everything above the `heart` is a description. The heart is the only code,
 * and it should be small: if a new connector needs much more than a hundred
 * lines, the engine is missing something and the engine is what should change.
 */
export type ConnectorContract = {
  /** Stable, never renamed: "apollo.find_people". */
  id: string;
  /** This connector's own version. Bumped when the heart changes. */
  version: string;
  job: ConnectorJob;
  label: string;
  description: string;
  provider: ProviderInfo;

  needs: ConnectorNeeds;
  produces: ConnectorOutput[];
  cost: CostModel;
  failure: FailurePolicy;
  limits: ConnectorLimits;
  rules: ConnectorRules;
  health: HealthProbe;
  execution: ExecutionStyle;

  /**
   * How widely this version is switched on.
   *
   * A change to a heart otherwise reaches every business at the same instant:
   * a provider ships v3, a developer updates the heart, and a thousand agents
   * change together mid-working-day with no way back but another deploy. So a
   * new version goes to our own account first, then a few, then everyone.
   */
  rollout: "internal" | "canary" | "everyone";

  heart: Heart;
  /** The probe's own heart — a known request whose answer we can check. */
  probe?: Heart;
};

/* -------------------------------------------------------------------------- */
/* Validation — a badly-formed connector must never ship                       */
/* -------------------------------------------------------------------------- */

/**
 * Check a contract before it is allowed to register.
 *
 * This runs at boot, not in a test, deliberately: a connector that cannot be
 * trusted should stop the deploy rather than wait to be discovered by a
 * customer whose agent quietly did nothing.
 */
export function validateConnector(contract: ConnectorContract): string[] {
  const problems: string[] = [];
  const id = contract.id || "(unnamed connector)";

  if (!/^[a-z0-9]+\.[a-z0-9_]+$/.test(contract.id ?? "")) {
    problems.push(`${id}: the id must look like "apollo.find_people".`);
  }
  if (!/^\d+\.\d+\.\d+$/.test(contract.version ?? "")) {
    problems.push(`${id}: version must be like "1.0.0" so a rollout can be staged.`);
  }
  if (!contract.provider?.apiVersion) {
    problems.push(`${id}: name the provider's API version, or nobody can tell what a deprecation affects.`);
  }
  if (!contract.provider?.docsUrl) {
    problems.push(`${id}: link the provider's docs — it is the first thing a maintainer opens.`);
  }
  if (!contract.produces?.length) {
    problems.push(`${id}: declare what it produces, or the engine cannot tell success from silence.`);
  }
  if (!contract.produces?.some((output) => output.required)) {
    problems.push(
      `${id}: at least one output must be required. With none, "it worked" and "it did nothing" are the same answer.`
    );
  }
  if (typeof contract.heart !== "function") {
    problems.push(`${id}: no heart — the one piece of code a connector must have.`);
  }
  if (contract.health && !contract.probe) {
    problems.push(`${id}: it declares a health check but has no probe to run.`);
  }
  if (contract.execution === "paged" && !contract.limits?.pageSize) {
    problems.push(`${id}: paged work needs a page size, or it will ask for everything at once.`);
  }
  if (contract.execution === "paged" && !contract.limits?.maxPages) {
    problems.push(`${id}: paged work needs a page ceiling, or a runaway list can spend without end.`);
  }
  if ((contract.limits?.callsPerDay ?? 0) <= 0) {
    problems.push(`${id}: a daily call limit is required. "Unlimited" is how a bill becomes a surprise.`);
  }
  if (contract.cost?.style !== "free" && !(contract.cost?.estimateCents > 0)) {
    problems.push(`${id}: a paid connector must estimate its cost, or no ceiling can be enforced.`);
  }

  // Secrets belong to the platform or to a connected account — never typed
  // into a field an architect can read back out of a saved workflow.
  for (const field of contract.needs?.architect ?? []) {
    if (field.kind === "secret") {
      problems.push(`${id}: "${field.key}" is a secret asked of the architect. Secrets belong in platform needs.`);
    }
  }

  return problems;
}

/** Every declared output key, for the engine's honesty check. */
export function requiredOutputKeys(contract: ConnectorContract): string[] {
  return contract.produces.filter((output) => output.required).map((output) => output.key);
}

/**
 * Did the heart actually return what it promised?
 *
 * The whole point. A connector that reports success while returning nothing is
 * how a business ends up believing a customer was texted, or that three
 * appointment slots were real.
 */
export function checkHeartResult(
  contract: ConnectorContract,
  result: HeartResult
): { ok: boolean; missing: string[] } {
  const missing = requiredOutputKeys(contract).filter((key) => {
    const value = result.outputs?.[key];
    if (value === undefined || value === null) return true;
    if (typeof value === "string" && value.trim() === "") return true;
    return false;
  });
  return { ok: missing.length === 0, missing };
}
