/**
 * THE NODE FRAME — one filled-in frame becomes a node, one engine runs them all.
 *
 * The vocabulary, so it stays straight:
 *
 *   A NODE FRAME is this shape — the blank form. Nine declarations and one
 *   function. It is what an architect fills in to describe a service.
 *
 *   A CONNECTOR is a filled-in frame. Apollo is a connector. Instantly is two.
 *   They live in the catalogue as files, or in an architect's own account as
 *   something they built through the Node Frame node in the builder.
 *
 *   A NODE is what appears on the canvas once a frame is filled in and passes
 *   validation.
 *
 * Before this, adding a service meant editing eight places: the registry, the
 * runner, the setup form, the dashboard, the cost, the failure handling, the
 * admin pricing and the tests. Eight chances to do it differently from last
 * time — which is how twenty hand-written handlers ended up in one 6,708-line
 * file, none of them agreeing on what to do when something breaks.
 *
 * A connector now declares nine things and provides one function. Everything
 * else — the business's setup form, their dashboard, the price ceiling, the
 * retries, the throttling, the daily health check, what an architect may test
 * — is generated by READING this declaration. Nothing is built per connector.
 *
 * Three rules shaped every decision here:
 *
 *  1. NAME THE JOB, NOT THE COMPANY. A connector declares that it
 *     "finds work emails", not that it "is Apollo". Apollo could be bought and
 *     shut down; an agent that asked for the job survives that, an agent that
 *     asked for the company dies with it.
 *
 *  2. PRETENDING TO WORK MUST BE IMPOSSIBLE. A connector cannot report success
 *     without returning what it declared it produces — the engine checks. This
 *     is the exact failure that had a calendar node inventing three appointment
 *     times when Google was unreachable, and logging it green.
 *
 *  3. WHAT AGES, DECLARE AS A KIND, NOT A VALUE. Credentials are turning from
 *     keys into OAuth tokens. Pricing is turning from per-call into per-token.
 *     So a connector says what KIND of credential it needs and what STYLE of
 *     metering it has — never "a key in a box" or a hardcoded rate.
 */

/* -------------------------------------------------------------------------- */
/* 01 · Who I am, and what job I do                                            */
/* -------------------------------------------------------------------------- */

/**
 * The job a connector performs, independent of who performs it.
 *
 * Apollo, Hunter and Prospeo are three companies doing ONE job. An agent asks
 * for the job; the platform picks a provider. Swapping providers then costs one
 * line instead of rebuilding every agent that used the old one.
 */
export type ConnectorJob =
  | "find-work-emails"
  | "verify-email"
  | "send-email-campaign"
  | "read-campaign-replies"
  | "scrape-website"
  | "enrich-company"
  | "send-message"
  | "place-call"
  | "book-meeting"
  | "search-web"
  | "custom";

export type ProviderInfo = {
  /** The company, in the words a person would use. */
  name: string;
  /** Where their documentation lives — the first thing a maintainer opens. */
  docsUrl: string;
  /** Their terms. Read before ever reselling their data under our own key. */
  termsUrl?: string;
  /**
   * The version of THEIR API this heart was written against.
   *
   * The single most useful field in this file. When a provider deprecates a
   * version, this is what tells a maintainer which connectors are affected —
   * without it, the answer is "read all of them".
   */
  apiVersion: string;
  /** When a human last confirmed this heart matches their current docs. */
  lastVerified: string;
};

/* -------------------------------------------------------------------------- */
/* 02 · What I need to run, and who supplies it                                */
/* -------------------------------------------------------------------------- */

/**
 * What KIND of credential, never the credential itself.
 *
 * Written as a kind because the industry is moving: today an API key, next
 * year an OAuth token that expires in an hour. A contract that assumed "a
 * string in a box" would need rewriting for every connector.
 */
export type CredentialKind = "api_key" | "oauth2" | "basic_auth" | "bearer_token" | "none";

export type PlatformNeed = {
  key: string;
  label: string;
  kind: CredentialKind;
  /** Shown to the admin who has to go and find it. */
  help: string;
  /** False when the connector can run without it (a free tier, say). */
  required: boolean;
};

/** A question put to a person — an architect or a business. */
export type ConnectorField = {
  key: string;
  label: string;
  help: string;
  kind:
    | "text"
    | "longtext"
    | "number"
    | "phone"
    | "email"
    | "url"
    | "date"
    | "time"
    | "choice"
    | "list"
    | "file"
    | "secret";
  required: boolean;
  choices?: string[];
  placeholder?: string;
  /** A default the person can change. Never a value they must not see. */
  defaultValue?: string | number;
};

/** An account the BUSINESS connects themselves — their Google, their Gmail. */
export type ConnectorAccount = {
  connector: string;
  label: string;
  help: string;
  scopes?: string[];
  optional?: boolean;
};

export type ConnectorNeeds = {
  /** Ours. Lives in the admin panel, never in the builder. */
  platform: PlatformNeed[];
  /**
   * The architect's decisions, made once for everyone who installs the agent.
   *
   * Manus's version of this design had two owners, business and admin. There
   * are three. The architect is the person who BUILDS on this platform, and
   * leaving them out breaks the model the whole product rests on.
   */
  architect: ConnectorField[];
  /** The business's own details. This list becomes their setup form. */
  business: ConnectorField[];
  /** Accounts the business connects with a button. */
  accounts: ConnectorAccount[];
};

/* -------------------------------------------------------------------------- */
/* 03 · What I produce                                                         */
/* -------------------------------------------------------------------------- */

/**
 * A value later steps can use.
 *
 * `sample` is not decoration: it is what lets the AI doors translate between
 * two steps that were never designed for each other, and what the engine
 * checks the heart's answer against.
 */
export type ConnectorOutput = {
  key: string;
  label: string;
  kind: "text" | "number" | "boolean" | "list" | "object" | "date";
  /** A realistic example. Used for translation and for validation. */
  sample: unknown;
  /** True when a run is meaningless without it — the engine enforces this. */
  required: boolean;
  /**
   * Where this value sits in the provider's answer, as a dot path.
   *
   * Only described connectors use it. The first output comes from the
   * recipe's `resultsAt`; every one after it used to be looked up by OUR name
   * for it — "skipped", "totalFound" — as though the provider used our words.
   * It never does, so a described card's second output was empty every run
   * and nothing said so. Named here, or left out and honestly reported as
   * absent.
   */
  at?: string;
};

/* -------------------------------------------------------------------------- */
/* 04 · What one run costs                                                     */
/* -------------------------------------------------------------------------- */

export type CostModel = {
  /** HOW it is charged, not how much — the how-much moves, the how does not. */
  style: "free" | "per_call" | "per_result" | "per_token" | "per_minute" | "per_month";
  /** Roughly, in US cents, so a ceiling can be enforced before the bill lands. */
  estimateCents: number;
  /** What one unit is, in plain words: "per lead found". */
  unit: string;
  /** Who is billed: the provider bills the business directly, or bills us. */
  billedTo: "business" | "platform";
  note?: string;
};

/* -------------------------------------------------------------------------- */
/* 05 · What to do when I fail                                                 */
/* -------------------------------------------------------------------------- */

export type FailurePolicy = {
  /**
   * retry — try again, it may be temporary.
   * skip  — this one item failed, carry on with the rest.
   * stop  — end the whole run; continuing would be wrong or expensive.
   */
  onError: "retry" | "skip" | "stop";
  maxRetries: number;
  backoffMs: number;
  /**
   * Errors that must NEVER be retried.
   *
   * A wrong key is still wrong on the fourth attempt, and retrying a "payment
   * required" four times is just four times the bill.
   */
  neverRetry: number[];
  /**
   * What the business is told when it finally fails. Written for them, not for
   * a developer — and never implying anything happened that did not.
   */
  humanMessage: string;
};

/* -------------------------------------------------------------------------- */
/* 06 · My limits                                                              */
/* -------------------------------------------------------------------------- */

export type ConnectorLimits = {
  callsPerMinute: number;
  callsPerDay: number;
  /** How many may be in flight at once for one business. */
  concurrent: number;
  /** For paged work: how many results to ask for at a time. */
  pageSize?: number;
  /** A hard ceiling on pages, so a runaway list cannot spend forever. */
  maxPages?: number;
};

/* -------------------------------------------------------------------------- */
/* 07 · What I must never do                                                   */
/* -------------------------------------------------------------------------- */

/**
 * The rules that protect the person at the other end, and the platform.
 *
 * NOT the same as a business setting. A business may choose to call fewer
 * people; a business may not choose to call people who never agreed. These are
 * enforced by the engine — a heart cannot switch them off, and neither can an
 * architect.
 */
export type ConnectorRules = {
  /** A consent record must exist for this person before we reach them. */
  requiresConsent?: boolean;
  /** Every message must carry a working way out. */
  requiresUnsubscribe?: boolean;
  /** Countries this connector must refuse to operate on. */
  blockedCountries?: string[];
  /** The most this may do for one business in a day, whatever they set. */
  hardDailyCap?: number;
  /*
   * There used to be a `testOnlyToVerifiedIdentity` rule here.
   *
   * It is gone because it became redundant, not because it stopped mattering.
   * The engine now answers a rehearsal itself, from each output's declared
   * `sample`, and never calls the heart — so a test cannot reach a real person
   * whatever the connector does. A structural guarantee beats a rule that has
   * to be declared, and a rule that can never fire is exactly the thing this
   * file refuses to carry.
   */

  /**
   * Config keys whose text must contain a way out, when requiresUnsubscribe is set.
   *
   * A rule the engine cannot look at anywhere is not a rule, it is a comment.
   * These two fields are what turn the flags above into something checkable —
   * and `validateNodeFrame` REFUSES a contract that declares a rule without
   * saying where to check it. That is the part that matters: the previous
   * version of this file declared four rules the engine never read, with a
   * comment claiming they were enforced. Making the declaration impossible to
   * fake is a stronger fix than remembering to read it.
   */
  unsubscribeIn?: string[];

  /**
   * Config keys holding the people this connector will reach.
   *
   * Phone numbers or email addresses, as a single value or a list. Used by the
   * country block and by the rehearsal guard.
   */
  reaches?: string[];

  /** Anything else a maintainer must know, in plain words. */
  notes?: string[];
};

/* -------------------------------------------------------------------------- */

/** Everything the rule check needs. No I/O — so it can be tested on its own. */
export type RuleContext = {
  config: Record<string, unknown>;
  isTest: boolean;
};

export type RuleVerdict = { ok: true } | { ok: false; rule: string; message: string };

/** Every value at a config key, flattened — a single value or a list. */
function targetsAt(config: Record<string, unknown>, keys: string[]): string[] {
  const out: string[] = [];
  for (const key of keys) {
    const value = config[key];
    if (Array.isArray(value)) {
      for (const item of value) {
        if (typeof item === "string") out.push(item.trim());
        else if (item && typeof item === "object") {
          // A list of people: {email, phone, ...}. Take the reachable parts.
          for (const field of ["email", "phone", "phoneNumber", "to"]) {
            const inner = (item as Record<string, unknown>)[field];
            if (typeof inner === "string" && inner.trim()) out.push(inner.trim());
          }
        }
      }
    } else if (typeof value === "string" && value.trim()) {
      for (const part of value.split(/[\n,;]/)) if (part.trim()) out.push(part.trim());
    }
  }
  return out;
}

/**
 * Which countries a dial code can belong to.
 *
 * Deliberately small: only the codes this platform actually operates in. An
 * unknown code is treated as unknown, not as safe — see below.
 */
const DIAL_CODES: Array<[string, string[]]> = [
  ["1", ["US", "CA"]],
  ["44", ["GB"]],
  ["91", ["IN"]],
  ["61", ["AU"]],
  ["64", ["NZ"]],
  ["65", ["SG"]],
  ["971", ["AE"]],
  ["49", ["DE"]],
  ["33", ["FR"]],
  ["34", ["ES"]],
  ["39", ["IT"]],
  ["31", ["NL"]],
  ["353", ["IE"]],
  ["81", ["JP"]],
  ["27", ["ZA"]],
  ["55", ["BR"]]
];

/** Countries a phone number might be in. Null when we genuinely cannot tell. */
function countriesForPhone(value: string): string[] | null {
  const digits = value.replace(/[^\d]/g, "");
  if (!digits) return null;
  // Longest code first, so 971 is not read as 97 or 9.
  const sorted = [...DIAL_CODES].sort((a, b) => b[0].length - a[0].length);
  for (const [code, countries] of sorted) if (digits.startsWith(code)) return countries;
  return null;
}

const LOOKS_LIKE_PHONE = /^\+?[\d\s().-]{7,}$/;
const WAY_OUT = /unsubscribe|opt[\s-]?out|\bstop\b|\{\{\s*unsubscribe/i;

/**
 * Check the rules that protect the person at the other end.
 *
 * Run BEFORE anything is spent and before the heart is touched. A rule that
 * fires here means nothing happened at all — no call, no charge, no record of
 * a message that was never sent.
 */
export function checkFrameRules(contract: NodeFrame, context: RuleContext): RuleVerdict {
  const rules = contract.rules ?? {};

  // ---- Consent ------------------------------------------------------------
  // The business is asked this in their own words on their own setup form.
  // Anything other than a clear yes is a no, including never having answered.
  if (rules.requiresConsent) {
    const answer = String(context.config.consentConfirmed ?? "").trim().toLowerCase();
    if (!answer.startsWith("yes")) {
      return {
        ok: false,
        rule: "requiresConsent",
        message:
          "This step only contacts people who agreed to be contacted, and that has not been confirmed yet. Nothing was sent. Confirm it on your setup page to switch this on."
      };
    }
  }

  // ---- A working way out --------------------------------------------------
  if (rules.requiresUnsubscribe) {
    for (const key of rules.unsubscribeIn ?? []) {
      const text = String(context.config[key] ?? "");
      if (!WAY_OUT.test(text)) {
        return {
          ok: false,
          rule: "requiresUnsubscribe",
          message:
            "Every message has to tell people how to stop receiving them, and this one does not. Nothing was sent. Add an unsubscribe line and it will go out on the next run."
        };
      }
    }
  }

  // ---- Countries we must not operate in -----------------------------------
  if (rules.blockedCountries?.length) {
    const blocked = new Set(rules.blockedCountries.map((code) => code.toUpperCase()));
    for (const target of targetsAt(context.config, rules.reaches ?? [])) {
      if (!LOOKS_LIKE_PHONE.test(target)) continue; // an email carries no country
      const countries = countriesForPhone(target);
      // Unknown is not the same as allowed. A blocklist exists because reaching
      // the wrong country is a legal problem, and "we could not tell" is not a
      // defence anyone has ever accepted.
      if (!countries || countries.some((country) => blocked.has(country))) {
        return {
          ok: false,
          rule: "blockedCountries",
          message:
            "One of these numbers is in a country this step is not allowed to contact, so nothing was sent."
        };
      }
    }
  }

  return { ok: true };
}

/* -------------------------------------------------------------------------- */
/* 08 · How to check I still work                                              */
/* -------------------------------------------------------------------------- */

/**
 * The daily self-test that replaces a human reading changelogs.
 *
 * A person watching for a provider's breaking change does it badly: they are
 * scanning release notes hoping to catch one line, for something that happens
 * twice a year. A tiny known request, run every day, catches the same thing
 * and never goes on holiday. The human still fixes it — they just stop being
 * the alarm.
 */
export type HealthProbe = {
  /** How often to check. */
  everyHours: number;
  /** The output keys the probe's answer must still contain. */
  expectKeys: string[];
  /** What it means for the platform when this fails. */
  severity: "breaks-agents" | "degrades" | "informational";
};

/* -------------------------------------------------------------------------- */
/* 09 · What shape of work I am                                                */
/* -------------------------------------------------------------------------- */

/**
 * immediate — answers in a moment.
 * paged     — returns results a page at a time.
 * polled    — takes minutes; start it, come back for the answer.
 * inbound   — the PROVIDER calls US. Not the node running: the world knocking.
 *
 * All four exist in the first agent this standard will serve: scraping is slow,
 * lead search is paged, and Instantly pushes replies to a webhook. A design
 * that only knew request-and-answer would be rebuilt within a week.
 */
export type ExecutionStyle = "immediate" | "paged" | "polled" | "inbound";

/* -------------------------------------------------------------------------- */
/* Inbound — when the provider calls US                                        */
/* -------------------------------------------------------------------------- */

/**
 * The third shape of work, and the one every hand-written connector rebuilt.
 *
 * Twilio knocks when a phone rings. Vapi knocks when a call ends. Calendly
 * knocks when someone books. Stripe knocks when someone pays. Instantly knocks
 * when a prospect replies. Each of those was written separately, with its own
 * idea of how to check the knock was genuine and its own way of not running
 * twice when the provider retried.
 *
 * A connector now declares that it is knocked on, and writes one function that
 * answers two questions: is this really from them, and what does it mean. The
 * platform supplies the address, the rate limit, the duplicate filter, the
 * paused-agent check and the run.
 */
export type InboundStyle = {
  /**
   * What a person is told to do with the address we give them.
   *
   * Written for the business, in their words, because they are the one who has
   * to go and paste it into somebody else's settings screen.
   */
  instructions: string;
  /** Events this connector understands. Anything else is acknowledged and ignored. */
  events?: string[];
  /**
   * The header carrying the shared secret, when the provider signs nothing.
   *
   * Not every provider signs its webhooks. Several let you attach a header of
   * your choosing instead, which is weaker than a signature but still proves
   * the sender knows something only we told them.
   */
  secretHeader?: string;
};

export type InboundContext = {
  /** The exact bytes as sent. Needed for any signature check. */
  rawBody: string;
  /** The body parsed as JSON, or the raw text when it is not JSON. */
  body: unknown;
  /** Lower-cased header names. */
  headers: Record<string, string>;
  /** The three owners' answers, same as a heart sees. */
  config: Record<string, unknown>;
  credentials: Record<string, string>;
  /** The secret this install told the provider to send back. */
  secret: string;
  log: (message: string, detail?: unknown) => void;
};

export type InboundResult = {
  /**
   * True when this event should start the agent.
   *
   * False is a normal, healthy answer, not a failure. Providers send far more
   * than anyone asked for — an "email opened" is not a reason to wake up a
   * workflow — and acknowledging without running is how a connector stays
   * cheap.
   */
  accepted: boolean;
  /** Why it was ignored. Shown in the log, never to a customer. */
  ignoredReason?: string;
  /** Named values, keyed exactly as `produces` declares. */
  outputs: Record<string, unknown>;
  /**
   * A stable id for this event, from the provider where possible.
   *
   * Providers retry. Without this, a retry is a second run: a second reply
   * handled, a second message sent, a second appointment booked.
   */
  eventId?: string;
};

/* -------------------------------------------------------------------------- */
/* The heart, and the contract that surrounds it                               */
/* -------------------------------------------------------------------------- */

/** What the engine hands the heart. Everything already resolved and checked. */
/* -------------------------------------------------------------------------- */
/* The one way a heart reaches the outside world                               */
/* -------------------------------------------------------------------------- */

/**
 * An error from a provider, carrying the status the engine needs.
 *
 * The status is not decoration. It is the single fact that decides whether
 * trying again is sensible: a 429 should back off and retry, a 401 will still
 * be wrong on the fourth attempt, and a 402 means retrying is just four times
 * the bill. A heart that throws a plain Error hides that, and the engine then
 * retries everything — including the things it must never retry.
 *
 * You do not construct this. `context.http` throws it for you.
 */
export class HttpError extends Error {
  /**
   * The status the engine reads to decide whether trying again is sensible.
   * A 429 backs off and retries; a 401 will still be wrong on the fourth
   * attempt; a 402 means retrying is just four times the bill.
   */
  readonly status: number;
  /** The provider's own error body, parsed when it was JSON. */
  readonly body: unknown;

  constructor(message: string, status: number, body: unknown) {
    super(message);
    this.name = "HttpError";
    this.status = status;
    this.body = body;
  }
}

export type HttpRequest = {
  url: string;
  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  headers?: Record<string, string>;
  /** Sent as JSON. Omit for a GET. */
  body?: unknown;
  /** Defaults to 20 seconds. */
  timeoutMs?: number;
};

export type HttpResponse = {
  status: number;
  /** Parsed JSON when the provider sent JSON, otherwise the raw text. */
  body: unknown;
  text: string;
};

/**
 * The ONLY way a heart may reach the network.
 *
 * A heart must never call `fetch` itself. Everything about talking to a
 * provider that the engine needs to do its job is handled here and cannot be
 * got wrong: errors carry their status, timeouts are applied, JSON is parsed,
 * and a rehearsal never reaches anybody.
 *
 * This is not a style preference. A connector written with raw `fetch` looks
 * correct, typechecks, passes validation, and then quietly retries a wrong API
 * key four times and emails real strangers during a test.
 */
export type HttpClient = {
  (request: HttpRequest): Promise<HttpResponse>;
  get(url: string, headers?: Record<string, string>): Promise<HttpResponse>;
  post(url: string, body?: unknown, headers?: Record<string, string>): Promise<HttpResponse>;
};

export type HeartContext = {
  /** Values from all three owners, merged and validated. */
  config: Record<string, unknown>;
  /** The resolved credential — the heart never looks one up itself. */
  credentials: Record<string, string>;
  /**
   * The only way to reach the provider. Never call `fetch` directly.
   *
   *   const answer = await context.http.post(url, { page: context.page }, {
   *     Authorization: `Bearer ${context.credentials.MY_KEY}`
   *   });
   *   const people = (answer.body as { people?: unknown[] }).people ?? [];
   *
   * A non-2xx throws an HttpError carrying `.status`, which is what tells the
   * engine whether to retry. You do not catch it — let it out.
   */
  http: HttpClient;
  /** Which page we are on, for paged work. */
  page: number;
  /** How many to ask the provider for — your declared `limits.pageSize`. */
  pageSize: number;
  /** A cursor the previous page returned, when the provider uses one. */
  cursor?: string;
  /**
   * True during a rehearsal.
   *
   * You almost certainly do not need this. The engine answers a rehearsal
   * itself, from the `sample` value on each declared output, and never calls
   * your heart at all — so a test cannot reach a real person even if you
   * forgot to think about it. Make your samples realistic and ignore this flag.
   */
  isTest: boolean;
  /** Structured logging. The heart never writes to the console. */
  log: (message: string, detail?: unknown) => void;
};

export type HeartResult = {
  /** Keyed by the `key` of each declared output. Checked before it is trusted. */
  outputs: Record<string, unknown>;
  /** For paged work: is there more to fetch? */
  morePages?: boolean;
  /** A cursor to hand to the next page. */
  cursor?: string;
  /** How many billable units this call actually consumed, if known. */
  unitsUsed?: number;
};

/** The one function a connector author writes. */
export type Heart = (context: HeartContext) => Promise<HeartResult>;

/**
 * What a self-test is given — and deliberately, what it is not.
 *
 * No config. A probe runs on a schedule with no business attached, so anything
 * a business would have typed simply is not there. Two fresh writers in a row
 * missed this in different ways: one reused the heart, the other invented a
 * literal "DUMMY_DATABASE_ID". Both produce the same result — a connector that
 * reports itself broken every morning until nobody reads the alerts.
 *
 * Leaving `config` out of this type is what turns that from a mistake you can
 * make into one the compiler refuses. A probe must be a call that needs
 * nothing but the credential. If the provider has no such call, say so in
 * `rules.notes` and set `health.severity` to "informational" — an honest gap
 * is worth more than a daily false alarm.
 */
export type ProbeContext = {
  credentials: Record<string, string>;
  http: HttpClient;
  log: (message: string, detail?: unknown) => void;
};

/**
 * An honest way out, for a provider with nothing to test against.
 *
 * Some APIs have no call you can make without a customer's own data — Notion
 * is one: every read needs a database id that belongs to a business. A writer
 * with no way to say that will invent a plausible literal
 * ("sample_database_id"), and the daily check then 404s every morning until
 * nobody reads the alerts.
 *
 * Saying it out loud is better. The connector is reported as unchecked with
 * this reason attached, which is the truth, and a maintainer can see at a
 * glance which providers we are flying blind on.
 */
export type ProbeResult = HeartResult | { cannotSelfTest: string };

export type Probe = (context: ProbeContext) => Promise<ProbeResult>;

/**
 * A whole connector.
 *
 * Everything above the `heart` is a description. The heart is the only code,
 * and it should be small: if a new connector needs much more than a hundred
 * lines, the engine is missing something and the engine is what should change.
 */
export type NodeFrame = {
  /** Stable, never renamed: "apollo.find_people". */
  id: string;
  /** This connector's own version. Bumped when the heart changes. */
  version: string;
  job: ConnectorJob;
  /** The full human name: "Add people to an Instantly campaign". */
  label: string;
  /**
   * A short name for the builder's sidebar card, where there is room for about
   * twelve characters on one line.
   *
   * Every other node in the library already has one written for that space.
   * Without it a connector card truncates to "Add people…" and the architect
   * cannot tell which service it belongs to — which is exactly what happened
   * with the first two: the word "Instantly" was cut off the card.
   *
   * THE RULE, set by the founder: use the company's name. "Apollo".
   * "Instantly". "Hunter". That is what an architect is looking for when they
   * scan the sidebar — not what the step does, which the card's tooltip and
   * the node itself already say.
   *
   * Only where one company has more than one node does a single extra word
   * follow, and only to separate them: "Instantly reply".
   */
  shortLabel?: string;
  description: string;
  provider: ProviderInfo;

  needs: ConnectorNeeds;
  produces: ConnectorOutput[];
  cost: CostModel;
  failure: FailurePolicy;
  limits: ConnectorLimits;
  rules: ConnectorRules;
  health: HealthProbe;
  execution: ExecutionStyle;

  /**
   * How widely this version is switched on.
   *
   * A change to a heart otherwise reaches every business at the same instant:
   * a provider ships v3, a developer updates the heart, and a thousand agents
   * change together mid-working-day with no way back but another deploy. So a
   * new version goes to our own account first, then a few, then everyone.
   */
  rollout: "internal" | "canary" | "everyone";

  /**
   * Where this frame came from.
   *
   * "catalogue" is one we wrote and shipped as a file. "architect" is one
   * somebody built through the Node Frame node in the builder.
   *
   * It is not decoration: an architect-built frame is NEVER given a platform
   * credential. Without that line, an architect could declare they need
   * OPENAI_API_KEY, point a request at their own server, and walk off with our
   * key. Their connector uses their own key or the business's, and nothing else.
   */
  source?: "catalogue" | "architect";

  heart: Heart;

  /**
   * How the provider is pointed at us. Required when execution is "inbound".
   */
  inbound?: InboundStyle;

  /**
   * The inbound heart: is this knock genuine, and what does it mean.
   *
   * Throw an error carrying `status: 401` when the request cannot be proved to
   * come from the provider — the platform turns that into a 401 and never
   * starts the agent. Everything else about receiving a webhook (the address,
   * the rate limit, the duplicate filter, whether the agent is paused, whether
   * the business is over its usage cap) is handled for you.
   */
  receive?: (context: InboundContext) => Promise<InboundResult> | InboundResult;
  /**
   * The daily self-test: one tiny known request, checked for shape.
   *
   * Required, and it must NOT be the heart. A probe runs with no business
   * config, so reusing the heart builds a URL out of undefined, gets a 404,
   * and reports the connector broken every morning until nobody reads the
   * alerts any more.
   */
  probe: Probe;
};

/* -------------------------------------------------------------------------- */
/* The AI doors a described connector is born with                             */
/* -------------------------------------------------------------------------- */

/**
 * The two doors for a node built from a frame.
 *
 * Every other node type has its doors hand-written in the registry, with a
 * fixed list of settings the entry door may fill in. A frame's settings are not
 * fixed — they are whatever the architect said this service needs — so the list
 * is built from the frame itself.
 *
 * That is still a real boundary, and for the same reason the fixed lists are:
 * the names come from what the ARCHITECT declared when they built the frame,
 * never from the run. A stranger typing into a published page can influence the
 * VALUES a door fills in; they can never widen which settings it may touch.
 *
 * Credentials are absent by construction — they live in `needs.platform`, not
 * in `needs.business`, so a door cannot reach the key that signs the request.
 */
export function doorsForFrame(frame: {
  label: string;
  description: string;
  provider: { name: string };
  needs: { business: Array<{ key: string; label: string }> };
  produces: Array<{ key: string; label: string }>;
}): { entry: { job: string; fields: string[] }; exit: { job: string } } {
  const fields = frame.needs.business.map((need) => need.key);
  const asked = frame.needs.business.map((need) => `${need.key} (${need.label})`).join(", ") || "none";
  const gives = frame.produces.map((output) => `${output.key} (${output.label})`).join(", ");

  return {
    entry: {
      fields,
      job:
        `This step calls ${frame.provider.name}: ${frame.description} ` +
        `Turn the customer's words and the run so far into exactly what this call needs. ` +
        `The settings you may fill in are: ${asked}. Leave every other setting exactly as it was saved. ` +
        `Two rules decide whether you change anything at all. First, if what is already saved reads correctly ` +
        `for what the customer gave, return no changes — the architect's own wording beats a guess. ` +
        `Second, when an earlier step already produced the exact id, code or reference this call needs, use ` +
        `that value word for word rather than a name, a search or a lookalike.`
    },
    exit: {
      job:
        `Clean ${frame.provider.name}'s raw reply into the smallest useful thing later steps can read. ` +
        (gives ? `This step is meant to produce: ${gives}. ` : "") +
        `Keep the names, numbers, ids, dates and links that answer what was asked; drop wrappers, ` +
        `repeated boilerplate and anything nobody will read.`
    }
  };
}

/* -------------------------------------------------------------------------- */
/* A frame filled in through the builder, rather than written as code          */
/* -------------------------------------------------------------------------- */

/**
 * The one request a described connector makes.
 *
 * A hand-written connector has a heart — real code. An architect filling in the
 * Node Frame node in the builder has no way to write code, so they describe the
 * request instead and the platform builds the heart from the description.
 *
 * Text fields may carry placeholders, filled at run time:
 *
 *   {{config.campaignId}}      an answer from the business's setup form
 *   {{credentials.ACME_KEY}}   a key, and ONLY one this frame itself declared
 *   {{page}} {{pageSize}} {{cursor}}   supplied by the engine for paged work
 *
 * This covers a plain REST call, which is what most services are. Anything
 * stranger still needs a written heart, and that is the honest boundary.
 */
export type FrameRecipe = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  /** Full https URL. Placeholders allowed. */
  url: string;
  /** Header name to value. This is where an API key usually goes. */
  headers?: Record<string, string>;
  /** Added to the query string. */
  query?: Record<string, string>;
  /** Sent as JSON. Placeholders allowed inside string values. */
  body?: Record<string, unknown>;
  /**
   * Where the useful part of the answer lives, as a dot path: "people",
   * "data.items". Empty means the whole body is the answer.
   */
  resultsAt?: string;
  /** How the provider hands over more than one page. */
  paging?: {
    style: "none" | "page" | "cursor";
    /** For "page": the parameter carrying the page number. */
    pageParam?: string;
    /** For "cursor": the parameter carrying the cursor we were given. */
    cursorParam?: string;
    /** Dot path to the next cursor in the answer. */
    cursorAt?: string;
    /** Dot path to a true/false "there is more" flag in the answer. */
    morePagesAt?: string;
  };
};

/**
 * Everything a form can produce: a whole frame except the code.
 *
 * The platform turns this into a real NodeFrame by building the heart from the
 * recipe, and then runs the SAME validation every hand-written connector goes
 * through. There is deliberately no second, weaker check for described
 * connectors — a node an architect built in the builder has to clear the same
 * bar as one we wrote ourselves, or it does not appear in their toolkit.
 */
export type NodeFrameDeclaration = Omit<NodeFrame, "heart" | "probe" | "receive"> & {
  recipe: FrameRecipe;
  /** A second, tiny request for the daily self-test. Optional and honest. */
  probeRecipe?: FrameRecipe;
  /** When the provider has no call that works without a customer's own data. */
  cannotSelfTest?: string;
};

/** Read "data.items" out of a parsed body. Undefined when the path is not there. */
export function valueAtPath(body: unknown, path?: string): unknown {
  if (!path) return body;
  let current: unknown = body;
  for (const step of path.split(".")) {
    if (current === null || typeof current !== "object") return undefined;
    current = (current as Record<string, unknown>)[step];
  }
  return current;
}

/**
 * Fill {{placeholders}} in one string.
 *
 * A placeholder that resolves to nothing becomes an empty string rather than
 * the literal "{{config.thing}}" — sending a provider the word "undefined" in
 * a URL produces a confusing 404 instead of an obvious empty value.
 */
export function fillPlaceholders(
  text: string,
  values: { config: Record<string, unknown>; credentials: Record<string, string>; page: number; pageSize: number; cursor?: string }
): string {
  /* A machine-drafted declaration writes JSON the honest way — a count is a
     NUMBER, a flag is a BOOLEAN — and this filler assumed every recipe value
     was a string, so `forecast_days: 1` crashed the whole call with
     "text.replace is not a function" (found live, first Open-Meteo proof,
     2026-08-26). A value with nothing to fill in passes through as itself. */
  if (typeof text !== "string") return String(text ?? "");
  return text.replace(/\{\{\s*([a-zA-Z0-9_.]+)\s*\}\}/g, (_match, token: string) => {
    if (token === "page") return String(values.page);
    if (token === "pageSize") return String(values.pageSize);
    if (token === "cursor") return values.cursor ?? "";
    if (token.startsWith("config.")) {
      const found = values.config[token.slice(7)];
      return found === undefined || found === null ? "" : String(found);
    }
    if (token.startsWith("credentials.")) return values.credentials[token.slice(12)] ?? "";
    return "";
  });
}

/**
 * Every credential name a recipe reaches for.
 *
 * Used to refuse a frame that reads a key it never declared — which is how an
 * architect could otherwise put {{credentials.OPENAI_API_KEY}} into a URL
 * pointing at their own server and walk off with the platform's key.
 */
export function credentialsUsedByRecipe(recipe: FrameRecipe): string[] {
  const text = JSON.stringify(recipe);
  const found = new Set<string>();
  for (const match of text.matchAll(/\{\{\s*credentials\.([a-zA-Z0-9_]+)\s*\}\}/g)) found.add(match[1]);
  return [...found];
}

/* -------------------------------------------------------------------------- */
/* Validation — a badly-formed connector must never ship                       */
/* -------------------------------------------------------------------------- */

/**
 * Check a contract before it is allowed to register.
 *
 * This runs at boot, not in a test, deliberately: a connector that cannot be
 * trusted should stop the deploy rather than wait to be discovered by a
 * customer whose agent quietly did nothing.
 */
export function validateNodeFrame(contract: NodeFrame): string[] {
  const problems: string[] = [];
  const id = contract.id || "(unnamed connector)";

  if (!/^[a-z0-9]+\.[a-z0-9_]+$/.test(contract.id ?? "")) {
    problems.push(`${id}: the id must look like "apollo.find_people".`);
  }
  if (!/^\d+\.\d+\.\d+$/.test(contract.version ?? "")) {
    problems.push(`${id}: version must be like "1.0.0" so a rollout can be staged.`);
  }
  if (!contract.provider?.apiVersion) {
    problems.push(`${id}: name the provider's API version, or nobody can tell what a deprecation affects.`);
  }
  if (!contract.provider?.docsUrl) {
    problems.push(`${id}: link the provider's docs — it is the first thing a maintainer opens.`);
  }
  // A card is one line of about twelve characters. A label longer than this
  // truncates, and the truncated part is usually the provider's name — the one
  // word that tells an architect what they are looking at.
  const cardLabel = contract.shortLabel ?? contract.label ?? "";
  if (cardLabel.length > 18) {
    problems.push(
      `${id}: "${cardLabel}" is too long for the sidebar card and will be cut off. Set shortLabel to the company's name — "Apollo", "Instantly".`
    );
  }
  if (!contract.produces?.length) {
    problems.push(`${id}: declare what it produces, or the engine cannot tell success from silence.`);
  }
  if (!contract.produces?.some((output) => output.required)) {
    problems.push(
      `${id}: at least one output must be required. With none, "it worked" and "it did nothing" are the same answer.`
    );
  }
  if (typeof contract.heart !== "function") {
    problems.push(`${id}: no heart — the one piece of code a connector must have.`);
  }
  /*
   * A probe that IS the heart.
   *
   * A fresh writer, given only this file, wrote `probe: heart` — which reads
   * like reuse and is a daily false alarm: the probe runs with no business
   * config, so the heart builds a URL out of undefined, gets a 404, and the
   * connector reports itself broken every morning until somebody stops reading
   * the alerts. A probe is a tiny call that needs nothing but the credential.
   */
  if (contract.probe && contract.probe === contract.heart) {
    problems.push(
      `${id}: the self-test is the same function as the heart. A probe runs with no business config, so it must be its own small call that needs only the credential.`
    );
  }

  /*
   * A heart that reaches the network itself.
   *
   * Everything the engine needs in order to do its job — the status that
   * decides whether a retry is sensible, the timeout, the rehearsal guard — is
   * in the client it hands you. A heart calling `fetch` looks correct,
   * typechecks, passes every other check here, and then retries a wrong API
   * key on every run because the status was left in a string.
   */
  if (typeof contract.heart === "function" && /\bfetch\s*\(/.test(contract.heart.toString())) {
    problems.push(
      `${id}: the heart calls fetch() directly. Use context.http — it carries the status the engine needs to decide whether retrying is sensible.`
    );
  }

  if (!/^\d{4}-\d{2}-\d{2}$/.test(contract.provider?.lastVerified ?? "")) {
    problems.push(`${id}: lastVerified must be a plain date like "2026-08-20" — it is what tells a maintainer how stale this is.`);
  }

  if (contract.execution === "paged" && !contract.limits?.pageSize) {
    problems.push(`${id}: paged work needs a page size, or it will ask for everything at once.`);
  }
  // An inbound connector with no way to read a knock is a dead address: the
  // business pastes it into their provider, the provider delivers, and nothing
  // happens for ever.
  if (contract.execution === "inbound") {
    if (typeof contract.receive !== "function") {
      problems.push(`${id}: it is inbound but has no receive() — nothing would ever read what the provider sends.`);
    }
    if (!contract.inbound?.instructions) {
      problems.push(`${id}: it is inbound but does not say what a business should do with the address we give them.`);
    }
  }
  if (contract.execution !== "inbound" && typeof contract.receive === "function") {
    problems.push(`${id}: it has a receive() but is not declared inbound, so it would never be called.`);
  }
  if (contract.execution === "paged" && !contract.limits?.maxPages) {
    problems.push(`${id}: paged work needs a page ceiling, or a runaway list can spend without end.`);
  }
  if ((contract.limits?.callsPerDay ?? 0) <= 0) {
    problems.push(`${id}: a daily call limit is required. "Unlimited" is how a bill becomes a surprise.`);
  }
  if (contract.cost?.style !== "free" && !(contract.cost?.estimateCents > 0)) {
    problems.push(`${id}: a paid connector must estimate its cost, or no ceiling can be enforced.`);
  }

  // Secrets belong to the platform or to a connected account — never typed
  // into a field an architect can read back out of a saved workflow.
  for (const field of contract.needs?.architect ?? []) {
    if (field.kind === "secret") {
      problems.push(`${id}: "${field.key}" is a secret asked of the architect. Secrets belong in platform needs.`);
    }
  }

  // A rule the engine has nowhere to look is a comment pretending to be a rule.
  //
  // This exact failure already happened here: four rules were declared, shown
  // to businesses on their setup form, and never read at run time — with a
  // comment above them claiming the engine enforced them. Refusing the
  // contract is what makes that impossible to repeat, because the connector
  // simply will not register.
  const rules = contract.rules ?? {};
  if (rules.requiresUnsubscribe && !rules.unsubscribeIn?.length) {
    problems.push(
      `${id}: it requires an unsubscribe but does not say which config key carries the message ("unsubscribeIn"), so nothing can check it.`
    );
  }
  if (rules.blockedCountries?.length && !rules.reaches?.length) {
    problems.push(
      `${id}: it blocks countries but does not say which config key holds the people it reaches ("reaches"), so nothing can check it.`
    );
  }
  for (const key of [...(rules.unsubscribeIn ?? []), ...(rules.reaches ?? [])]) {
    const known =
      (contract.needs?.business ?? []).some((field) => field.key === key) ||
      (contract.needs?.architect ?? []).some((field) => field.key === key) ||
      (contract.produces ?? []).some((output) => output.key === key);
    if (!known) {
      problems.push(
        `${id}: a rule points at "${key}", which this connector never asks for or produces. A rule aimed at nothing passes every time.`
      );
    }
  }

  return problems;
}

/** Every declared output key, for the engine's honesty check. */
export function requiredOutputKeys(contract: NodeFrame): string[] {
  return contract.produces.filter((output) => output.required).map((output) => output.key);
}

/**
 * Did the heart actually return what it promised?
 *
 * The whole point. A connector that reports success while returning nothing is
 * how a business ends up believing a customer was texted, or that three
 * appointment slots were real.
 */
export function checkHeartResult(
  contract: NodeFrame,
  result: HeartResult
): { ok: boolean; missing: string[] } {
  const missing = requiredOutputKeys(contract).filter((key) => {
    const value = result.outputs?.[key];
    if (value === undefined || value === null) return true;
    if (typeof value === "string" && value.trim() === "") return true;
    return false;
  });
  return { ok: missing.length === 0, missing };
}
