import {
  Activity,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CircleCheck,
  CircleDollarSign,
  Clock,
  Cloud,
  Code,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Download,
  Eye,
  FileText,
  Flame,
  Folder,
  Gauge,
  Gem,
  Gift,
  Globe,
  Handshake,
  Headphones,
  Heart,
  House,
  Image as ImageIcon,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Key,
  Landmark,
  Laptop,
  Layers,
  LayoutDashboard,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link as LinkIcon,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  MousePointerClick,
  Music,
  Network,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  PenTool,
  Percent,
  Phone,
  PiggyBank,
  Play,
  Plug,
  Plus,
  Puzzle,
  QrCode,
  Quote,
  Radar,
  Receipt,
  RefreshCw,
  Rocket,
  Route,
  Ruler,
  Scale,
  School,
  ScanLine,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Signal,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  Speech,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Table,
  Tag,
  Target,
  Telescope,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  University,
  Upload,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wand,
  Watch,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon
} from "lucide-react";

/**
 * The icon vocabulary a spec may name.
 *
 * A curated map rather than lucide's full 1700-icon barrel: importing the
 * barrel to look a name up at runtime would ship every icon in the library to
 * every visitor. These are the ones a product page actually reaches for, and
 * an unknown name resolves to `Sparkles` instead of a hole in the layout —
 * a spec can never break a page by naming an icon that does not exist.
 *
 * Keys are kebab-case. `resolveIconName` normalizes whatever the AI wrote
 * ("ShieldCheck", "shield_check", "Shield Check") into that form, so the model
 * does not have to know our spelling.
 */
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  award: Award,
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bell: Bell,
  blocks: Blocks,
  "book-open": BookOpen,
  bot: Bot,
  boxes: Boxes,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  camera: Camera,
  chart: ChartBar,
  "chart-bar": ChartBar,
  "bar-chart": ChartBar,
  "chart-line": ChartLine,
  "line-chart": ChartLine,
  "chart-pie": ChartPie,
  "pie-chart": ChartPie,
  check: Check,
  "check-circle": CircleCheck,
  "circle-check": CircleCheck,
  "circle-dollar-sign": CircleDollarSign,
  dollar: CircleDollarSign,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  "credit-card": CreditCard,
  crown: Crown,
  database: Database,
  download: Download,
  eye: Eye,
  "file-text": FileText,
  file: FileText,
  document: FileText,
  flame: Flame,
  fire: Flame,
  folder: Folder,
  gauge: Gauge,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  handshake: Handshake,
  headphones: Headphones,
  support: Headphones,
  heart: Heart,
  home: House,
  house: House,
  image: ImageIcon,
  photo: ImageIcon,
  inbox: Inbox,
  infinity: InfinityIcon,
  info: Info,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  dashboard: LayoutDashboard,
  leaf: Leaf,
  library: Library,
  "life-buoy": LifeBuoy,
  lightbulb: Lightbulb,
  idea: Lightbulb,
  link: LinkIcon,
  list: List,
  lock: Lock,
  mail: Mail,
  email: Mail,
  map: Map,
  "map-pin": MapPin,
  location: MapPin,
  medal: Medal,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  chat: MessageSquare,
  mic: Mic,
  microphone: Mic,
  monitor: Monitor,
  "mouse-pointer-click": MousePointerClick,
  click: MousePointerClick,
  music: Music,
  network: Network,
  newspaper: Newspaper,
  package: Package,
  paintbrush: Paintbrush,
  palette: Palette,
  "pen-tool": PenTool,
  percent: Percent,
  phone: Phone,
  "piggy-bank": PiggyBank,
  play: Play,
  plug: Plug,
  plus: Plus,
  puzzle: Puzzle,
  "qr-code": QrCode,
  quote: Quote,
  radar: Radar,
  receipt: Receipt,
  refresh: RefreshCw,
  "refresh-cw": RefreshCw,
  rocket: Rocket,
  route: Route,
  ruler: Ruler,
  scale: Scale,
  school: School,
  "scan-line": ScanLine,
  scan: ScanLine,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  "share-2": Share2,
  share: Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  signal: Signal,
  sliders: SlidersHorizontal,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  mobile: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  sparkle: Sparkles,
  magic: Sparkles,
  speech: Speech,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  table: Table,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  timer: Timer,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  university: University,
  upload: Upload,
  user: User,
  "user-check": UserCheck,
  users: Users,
  team: Users,
  video: Video,
  wallet: Wallet,
  wand: Wand,
  "wand-2": Wand,
  wand2: Wand,
  watch: Watch,
  webhook: Webhook,
  wifi: Wifi,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
  bolt: Zap
};

/** The stand-in for a name we do not carry. Decorative, never wrong-looking. */
export const FALLBACK_ICON: LucideIcon = Sparkles;

/**
 * "ShieldCheck" / "shield_check" / "Shield Check" / "SHIELD-CHECK" all become
 * "shield-check". CamelCase boundaries are split before the lowercase pass so
 * the AI's most natural spelling (the lucide component name) works as written.
 */
export function normalizeIconName(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Never returns null — an unknown name resolves to the fallback. */
export function resolveIcon(name: string | undefined | null): LucideIcon {
  if (!name) return FALLBACK_ICON;
  return ICONS[normalizeIconName(name)] ?? FALLBACK_ICON;
}

/** True when the spec named an icon we actually carry (tests, builder hints). */
export function hasIcon(name: string | undefined | null): boolean {
  return Boolean(name) && normalizeIconName(String(name)) in ICONS;
}

export const ICON_NAMES: readonly string[] = Object.keys(ICONS);
