import {
  asString,
  extractTimeLabel,
  hasVariable,
  humanSlotLabel,
  mentionsSpecificTime,
  pickOfferedSlot,
  setVariables,
  stringVariable,
  type AgentRuntimeContext,
  type NodeExecutionResult
} from "./runtime-context";
import { nodeCapability, nodeLabel, nodeRequiredVariables, type GraphNode } from "./tool-registry";
import type { AgentProviders } from "./provider-adapters";

function log(
  context: AgentRuntimeContext,
  node: GraphNode,
  status: "success" | "waiting" | "error",
  message: string,
  output?: unknown
): void {
  context.executedNodes.push({
    nodeId: node.id,
    label: nodeLabel(node, node.id),
    status,
    message,
    output
  });
}

/** Resolve {{variable}} references in node templates from the runtime context. */
export function resolveTemplate(template: string, context: AgentRuntimeContext): string {
  const values: Record<string, string> = {
    "customer.name": stringVariable(context, "customer.name") || context.caller.name,
    "customer.phone": stringVariable(context, "customer.phone") || context.caller.phone,
    "caller.name": context.caller.name,
    "caller.phone": context.caller.phone,
    service: stringVariable(context, "service"),
    "appointment.service": stringVariable(context, "service"),
    "appointment.date": stringVariable(context, "appointment.date"),
    "appointment.time": stringVariable(context, "appointment.time"),
    "appointment.confirmation_id": stringVariable(context, "appointment.confirmation_id"),
    "selected.slot": stringVariable(context, "selected.slot"),
    "business.name": context.business.name,
    "business_name": context.business.name,
    "businessName": context.business.name,
    "business.type": context.business.type,
    "business_type": context.business.type,
    "assistant_name": context.business.assistantName,
    "assistantName": context.business.assistantName
  };

  let resolved = template;

  for (const [key, value] of Object.entries(values)) {
    resolved = resolved.replaceAll(`{{${key}}}`, value);
  }

  return resolved;
}

/**
 * Fill runtime variables from inferred conversation state so node gating can
 * be purely metadata-driven (requiredVariables present -> node may run).
 */
export function seedConversationVariables(context: AgentRuntimeContext): void {
  const { conversation } = context;

  setVariables(context, {
    "conversation.latest_user_message": context.userMessage,
    ...(conversation.collectedName ? { "customer.name": conversation.collectedName } : {}),
    ...(conversation.collectedPhone ? { "customer.phone": conversation.collectedPhone } : {}),
    ...(conversation.requestedService ? { service: conversation.requestedService } : {})
  });
}

type NodeHandler = (
  node: GraphNode,
  context: AgentRuntimeContext,
  providers: AgentProviders
) => Promise<NodeExecutionResult>;

const handlePhoneTrigger: NodeHandler = async (node, context) => {
  log(context, node, "success", "Call message received by the workflow trigger (no telephony provider used in this mode).", {
    callerName: context.caller.name,
    callerPhone: context.caller.phone,
    channel: context.channel,
    message: context.userMessage
  });

  setVariables(context, {
    "caller.phone": context.caller.phone,
    "caller.name": context.caller.name,
    "call.time": new Date().toISOString(),
    "business.name": context.business.name,
    "business.type": context.business.type
  });

  return { status: "executed" };
};

const handleSmsTrigger: NodeHandler = async (node, context) => {
  log(context, node, "success", "Message treated as an incoming SMS (no telephony provider used in this mode).", {
    from: context.caller.phone,
    body: context.userMessage
  });

  setVariables(context, {
    "customer.phone": context.caller.phone,
    "sms.incoming_message": context.userMessage,
    "sms.received_time": new Date().toISOString(),
    "trigger.source": "sms"
  });

  return { status: "executed" };
};

const handleAiConversation: NodeHandler = async (node, context) => {
  // The reply itself is generated by the graph runner after all connected tool
  // nodes have had their chance to run, so it can reflect their results.
  log(context, node, "success", "Conversation handled by this node's prompt and the connected downstream tools.", {
    assistantName: context.business.assistantName,
    schedulingIntent: context.conversation.schedulingIntent,
    latestUserMessage: context.userMessage
  });

  return { status: "executed" };
};

const handleCalendarAvailability: NodeHandler = async (node, context, providers) => {
  const { conversation, turn } = context;

  // Runs only when the caller is actively scheduling this turn.
  if (!conversation.schedulingIntent || !conversation.currentContributes || conversation.ending) {
    return { status: "skipped" };
  }

  // Scheduling settings come from node config / buyer setup — never fixed.
  const maxSlots =
    Number(node.data?.maximumSlotsToShow) ||
    Number(node.data?.maxSlotsToShow) ||
    Number(node.data?.slotsToOffer) ||
    6;

  const result = await providers.calendar.checkAvailability({
    calendarId: asString(node.data?.calendarId) || context.business.calendarId,
    timeZone: context.business.timezone,
    date: conversation.requestedDate,
    maxSlots,
    bufferMinutes: Number(node.data?.bufferMinutes) || 10,
    openHour: Number(node.data?.openHour) || undefined,
    closeHour: Number(node.data?.closeHour) || undefined,
    durationMinutes: Number(node.data?.serviceDurationMinutes) || Number(node.data?.defaultDurationMinutes) || undefined
  });

  setVariables(context, {
    "calendar.available_slots": result.slots,
    "calendar.requested_date": conversation.requestedDate,
    "calendar.timezone": context.business.timezone
  });

  // Resolve the caller's chosen time against the offered slots; honor a stated
  // time that is not in the list rather than silently booking the wrong slot.
  if (conversation.lastTimeMessage) {
    const offered = pickOfferedSlot(conversation.lastTimeMessage, result.slots);
    const stated = extractTimeLabel(conversation.lastTimeMessage);
    const selected = offered || (stated ? `${conversation.requestedDate} ${stated}` : "");

    if (selected) setVariables(context, { "selected.slot": selected });
  }

  turn.slotsOffered = true;

  context.toolCalls.push({
    name: "calendar.check_availability",
    status: "simulated",
    message: result.note,
    input: { calendarId: context.business.calendarId, date: conversation.requestedDate, timeZone: context.business.timezone },
    output: { slots: result.slots, source: result.source }
  });

  log(context, node, "success", `Found ${result.slots.length} open slots (${result.source === "calendar" ? "connected calendar" : "test data"}).`, {
    slots: result.slots,
    source: result.source
  });

  return { status: "executed" };
};

const handleBookAppointment: NodeHandler = async (node, context, providers) => {
  const { conversation, turn } = context;

  if (!conversation.schedulingIntent || !conversation.currentContributes || conversation.ending) {
    return { status: "skipped" };
  }

  // Workflows without a Calendar Availability node still honor a stated time.
  if (!hasVariable(context, "selected.slot") && conversation.lastTimeMessage) {
    const stated = extractTimeLabel(conversation.lastTimeMessage);

    if (stated) setVariables(context, { "selected.slot": `${conversation.requestedDate} ${stated}` });
  }

  const required = nodeRequiredVariables(node);
  const missing = required.filter((key) => !hasVariable(context, key));

  if (missing.length > 0) {
    turn.missingVariables = missing;
    // Booking is the gate: downstream nodes wait until required inputs exist.
    return { status: "waiting" };
  }

  const slot = stringVariable(context, "selected.slot");
  const result = await providers.calendar.bookAppointment({
    calendarId: context.business.calendarId,
    timeZone: context.business.timezone,
    slot,
    service: stringVariable(context, "service"),
    customerName: stringVariable(context, "customer.name"),
    customerPhone: stringVariable(context, "customer.phone")
  });

  const slotParts = slot.match(/^(\d{4}-\d{2}-\d{2})\s+(.+)$/);

  setVariables(context, {
    "appointment.status": result.status,
    "appointment.confirmation_id": result.confirmationId,
    "appointment.date": slotParts?.[1] ?? conversation.requestedDate,
    "appointment.time": slotParts?.[2] ?? slot,
    "appointment.calendar_event_id": result.calendarEventId
  });

  turn.bookedThisTurn = result.status === "confirmed";

  context.toolCalls.push({
    name: "calendar.book_appointment",
    status: "simulated",
    message: result.note,
    input: {
      customerName: stringVariable(context, "customer.name"),
      customerPhone: stringVariable(context, "customer.phone"),
      service: stringVariable(context, "service"),
      slot
    },
    output: {
      status: result.status,
      confirmationId: result.confirmationId,
      date: stringVariable(context, "appointment.date"),
      time: stringVariable(context, "appointment.time")
    }
  });

  log(context, node, "success", "Booked appointment through the calendar provider (dry run in test mode).", {
    slot,
    status: result.status
  });

  return { status: "executed" };
};

const handleSendSms: NodeHandler = async (node, context, providers) => {
  const { conversation, turn } = context;

  const required = nodeRequiredVariables(node);
  const missing = required.filter((key) => !hasVariable(context, key));

  // SMS runs when a prior node produced something to notify about this turn,
  // or the caller explicitly asked to be texted — and its inputs exist.
  const shouldRun = turn.bookedThisTurn || (conversation.smsRequested && !conversation.ending);

  if (!shouldRun) return { status: "skipped" };

  if (missing.length > 0) {
    turn.missingVariables = missing;
    return { status: "waiting" };
  }

  const template =
    asString(node.data?.customerTemplate) ||
    asString(node.data?.patientTemplate) ||
    asString(node.data?.smsBody);

  const body = template
    ? resolveTemplate(template, context)
    : turn.bookedThisTurn
      ? `Your ${stringVariable(context, "service")} is confirmed for ${humanSlotLabel(stringVariable(context, "selected.slot"))}. — ${context.business.name}`
      : `Thanks for contacting ${context.business.name}. We will follow up shortly.`;

  const to = stringVariable(context, "customer.phone") || context.caller.phone;
  const result = await providers.sms.send({ to, body });

  setVariables(context, { "sms.status": result.status, "sms.body": body });
  turn.smsThisTurn = true;

  context.toolCalls.push({
    name: "sms.send",
    status: "simulated",
    message: result.note,
    input: { to },
    output: { body, status: result.status }
  });

  log(context, node, "success", "Prepared SMS through the SMS provider (dry run in test mode).", { to, body });

  return { status: "executed" };
};

const handleEndFlow: NodeHandler = async (node, context) => {
  const { conversation, turn } = context;

  if (!conversation.ending) return { status: "skipped" };

  const closingMessage = asString(node.data?.closingMessage);

  setVariables(context, { "flow.status": "completed", "flow.closing_message": closingMessage });
  turn.endReached = true;

  log(context, node, "success", "Caller ended the conversation. Flow reached the end node.");

  return { status: "ended" };
};

const handleCondition: NodeHandler = async (node, context) => {
  log(context, node, "success", "Passed through condition node.");
  return { status: "executed" };
};

const handleUnknown: NodeHandler = async (node, context) => {
  log(context, node, "waiting", "Not part of this conversation channel; skipped by the runtime.");
  return { status: "skipped" };
};

const HANDLERS: Record<string, NodeHandler> = {
  "trigger.phone_call": handlePhoneTrigger,
  "trigger.sms": handleSmsTrigger,
  "ai.conversation": handleAiConversation,
  "calendar.check_availability": handleCalendarAvailability,
  "calendar.book_appointment": handleBookAppointment,
  "sms.send": handleSendSms,
  "flow.end": handleEndFlow,
  "logic.condition": handleCondition
};

export async function executeNode(
  node: GraphNode,
  context: AgentRuntimeContext,
  providers: AgentProviders
): Promise<NodeExecutionResult> {
  context.currentNodeId = node.id;

  const handler = HANDLERS[nodeCapability(node)] ?? handleUnknown;

  try {
    return await handler(node, context, providers);
  } catch (error) {
    log(context, node, "error", error instanceof Error ? error.message : "Node execution failed.");
    return { status: "failed" };
  }
}
